#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                    <aegis.ist>
#     .\_/.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: main
        image: localhost:5000/example-using-sidecar:0.17.2
      - name: sidecar
        image: localhost:5000/aegis-ist-sidecar:0.17.2
