#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                    <aegis.ist>
#     .\_/.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: default
  labels:
    app.kubernetes.io/name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example
    spec:
      serviceAccountName: example
      containers:
      - name: main
        image: aegishub/example-using-init-container:0.16.0
        env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: aegis-secret-example
              key: VALUE
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: aegis-secret-example
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: aegis-secret-example
              key: PASSWORD

      initContainers:
      # See `./register.sh` to register the workload and finalize
      # this init container.
      - name: init-container
        image: aegishub/aegis-ist-init-container:0.16.0
        volumeMounts:
        # Volume mount for SPIRE unix domain socket.
        - name: spire-agent-socket
          mountPath: /spire-agent-socket
          readOnly: true
        #
        # You can configure Aegis Init Container by providing environment 
        # variables.
        #
        # See https://aegis.ist/docs/configuration for more information
        # about these environment variables.
        #
        # When you don’t explicitly provide env vars here, Aegis Init Container
        # will assume the default values outlined in the given link above.
        #
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///spire-agent-socket/agent.sock"
        - name: AEGIS_LOG_LEVEL
          value: "7"
        - name: AEGIS_WORKLOAD_SVID_PREFIX
          value: "spiffe://aegis.ist/workload/"
        - name: AEGIS_SAFE_SVID_PREFIX
          value: "spiffe://aegis.ist/workload/aegis-safe/ns/aegis-system/sa/aegis-safe/n/"
        - name: AEGIS_INIT_CONTAINER_POLL_INTERVAL
          value: "5000"
      volumes:
      # Using SPIFFE CSI Driver to bind to the SPIRE Agent Socket
      # ref: https://github.com/spiffe/spiffe-csi
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
