#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                    <aegis.ist>
#     .\_/.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: main
        image: localhost:5000/example-using-init-container:0.18.1
      initContainers:
      - name: init-container
        image: localhost:5000/aegis-ist-init-container:0.18.1
