#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                    <aegis.ist>
#     .\_/.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-safe
  namespace: aegis-system
spec:
  template:
    spec:
      containers:
        - name: main
          image: aegishub/aegis-ist-fips-safe:0.18.2
