#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                  <aegis.z2h.dev>
#     .\_/.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-safe
  namespace: aegis-system
automountServiceAccountToken: false
