#!/usr/bin/env bash

#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                  <aegis.z2h.dev>
#     .\_/.
#

# TODO: probably we need an “unregister” API too.

# `notary` -> `safe`

# The workload API is used by `notary` to register a workload to `safe`.
# `safe` will not dispatch secrets to a workload if it is not registered.
#  `workloadId` and `workloadToken` are generated by `notary`.
http PUT http://localhost:8017/v1/workload \
  token=SecureWorkloadToken \
  workloadId=NotaryGeneratedRandomWorkloadId \
  workloadSecret=NotaryGeneratedSecureWorkloadToken