#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                    <aegis.ist>
#     .\_/.
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - Deployment.yaml
patches:
  - path: image-override-ist-remote.yaml
generatorOptions:
  disableNameSuffixHash: true
