#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                    <aegis.ist>
#     .\_/.
#

# !!!
# !!! Keeping the `aegis-safe-age-key` Secret secure is critical
# !!! for production deployments. See the following link for details:
# !!!
# !!! https://aegis.ist/production/#restrict-access-to-aegis-safe-age-key
# !!!
apiVersion: v1
kind: Secret
metadata:
  name: aegis-safe-age-key
  namespace: aegis-system
type: Opaque
data:
  # '{}' (e30=) is a special placeholder to tell Safe that the Secret
  # is not initialized. DO NOT remove or change it.
  KEY_TXT: "e30="
